### ISSUE TITLE
Create Glossary for acronyms and terms

### ISSUE THREAD

**Issue by pwilkins** [mitodl/handbook#2]
I would value having a resource that provided annotated definitions of terms.  Ideally it would focus on those terms that a Google search wouldn't turn up, like what RPC, or bees with machine guns.  Also, for those terms that Google would find, annotations to provide ODL context.

**Comment by justinabrahms** [comment]
I'd say that the best way to do this would be to create a PR with a list of terms that you want and other people can contribute definitions for them as part of the code review. Does that sound like it would work for you?

**Comment by pwilkins** [comment]
Yes, that was my next step.  I was just following our practice for creating an issue before creating a PR.  :-)  

Though we dispense will all these niceties when updating Doof.

**Comment by pdpinch** [comment]
We have a glossary now, at https://github.com/mitodl/hq/discussions/159
