### ISSUE TITLE
New Testing Approach: Pytest and Selenium

### ISSUE THREAD

**Issue by gsidebo** [mitodl/handbook#22]
I'd like to discuss the benefits (and drawbacks) of pytest vs. the standard unittest library, with specific examples using the Micromasters codebase and a discussion on the steps we might need to take in order to 'migrate'. This would have a fair amount of overlap with #20 and possibly #21 

Selenium can be sort of an optional topic for this one. The flexibility of the pytest framework gives us the opportunity to write and invoke Selenium tests in some really useful ways, so it may be worth discussing.

**Comment by pdpinch** [comment]
Should we close this now? 

I know we had some takeaways from the presentation, like https://github.com/mitodl/micromasters/issues/2794. Is there anything else that should get captured (either here or elsewhere)?
