### ISSUE TITLE
Knowledge bases and documentation

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/handbook#23]
Discuss tools and processes for building and maintaining a knowledge base and/or system of documentation for information that is not necessarily constrained to a single project.

**Comment by blarghmatey** [comment]
Possible contenders for tooling:
- https://github.com/airbnb/knowledge-repo
- https://www.atlassian.com/software/confluence
- https://www.notion.so/
- https://taiga.io/
- http://raneto.com/

**Comment by blarghmatey** [comment]
Might also be worth discussing alternative tools for higher level project management. We often abuse Github issues for tasks that have nothing to do with a given project or its code and doesn't necessarily need to be public information.

**Comment by gsidebo** [comment]
Notes from this meeting: https://docs.google.com/document/d/1r3S7RsJapA3H5v8crAzcfS9M_hYRCvLsLQHvE3EeNdE/edit
